/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewFrame;

import view.LoginForm;
import controller.BookController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Librarian;

/**
 *
 * @author Duong
 */
public class BookSearchForm extends javax.swing.JFrame {
   BookController bookController = new BookController();
    /**
     * Creates new form BookSearchForm
     */
    public BookSearchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchMode = new javax.swing.JComboBox<>();
        searchKey = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notFoundButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        searchLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setText("Tìm kiếm theo");
        jPanel1.add(searchLabel);
        searchLabel.setBounds(112, 180, 110, 25);

        searchMode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sách", "Tên sách", "Tên tác giả", "Thể loại" }));
        jPanel1.add(searchMode);
        searchMode.setBounds(240, 180, 113, 28);
        jPanel1.add(searchKey);
        searchKey.setBounds(370, 180, 227, 30);

        searchButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchButton.setText("Tìm");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(610, 180, 70, 31);

        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginButton.setText("Đăng nhập");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(940, 40, 120, 31);

        bookTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Thể loại", "Nhà xuất bản", "Năm xuất bản", "Tiền đặt cọc", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(27, 230, 1046, 169);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trường đại học Bách Khoa Hà Nội");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(273, 30, 501, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thư viện Tạ Quang Bửu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(387, 90, 344, 42);

        notFoundButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        notFoundButton.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(notFoundButton);
        notFoundButton.setBounds(410, 420, 290, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        notFoundButton.setText("");
        String mode = "";
        String[] colBook = {"Mã sách", "Tên sách", "Tác giả", "Thể loại",
            "Nhà Xuất bản", "Năm xuất bản",  "Tiền đặt cọc", "Tình trạng"};
        DefaultTableModel model = new DefaultTableModel(colBook, 0);
        
        switch(searchMode.getSelectedItem().toString()){
            case "Mã sách": mode = "MaSach";
                            break;
            case "Tên sách": mode = "TenSach";
                             break;
            case "Tên tác giả": mode = "TacGia";
                                break;
            case "Thể loại": mode = "TheLoai";
                             break;
        }
        ArrayList<Book> result = bookController.searchBook(mode, searchKey.getText());
        if(result.size() == 0){
            notFoundButton.setText("Không tìm thấy kết quả");
        }else{
           int i;
           Object[] objBookAtt = new Object[8];
           for(i=0; i<result.size(); i++){
               objBookAtt[0] = result.get(i).getID();
               objBookAtt[1] = result.get(i).getName();
               objBookAtt[2] = result.get(i).getAuthor();
               objBookAtt[3] = result.get(i).getCategory();               
               objBookAtt[4] = result.get(i).getPublisher();                 
               objBookAtt[5] = result.get(i).getPublishingYear();               
               objBookAtt[6] = result.get(i).getDeposit();
               objBookAtt[7] = result.get(i).getStatus();
               model.addRow(objBookAtt);
            }           
        //   bookTable.setModel(model);
        }
        bookTable.setModel(model);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setModal(true);
        loginForm.setLocationRelativeTo(this);
        loginForm.setVisible(true);
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel notFoundButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchKey;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JComboBox<String> searchMode;
    // End of variables declaration//GEN-END:variables
}
