/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BookController;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Librarian;

/**
 *
 * @author Duong
 */
public class MainView extends javax.swing.JFrame {

    private static Librarian currentUser;
    private ChangePasswordForm changePasswordPanel;
    private BooksearchForm booksearchPanel;
    private LibrarianDataForm librarianDataPanel;
    private BookManagementForm bookManagementPanel;
    private LibrarianManagementForm librarianManagementPanel;
    private ReaderManagementForm readerManagementPanel;
    private ReportForm reportPanel;
    private StatisticForm statisticPanel;
    private BillManagementForm billManagementPanel;
    private boolean loginSuccess;

    public static void setCurrentUser(Librarian currentUser) {
        MainView.currentUser = currentUser;
    }

    public static Librarian getCurrentUser() {
        return currentUser;
    }

    /**
     * Creates new form mainView
     */
    public MainView() {
        initComponents();
        CardLayout card = new CardLayout();
        mainViewPanel.setLayout(card);
        booksearchPanel = new BooksearchForm();
        changePasswordPanel = new ChangePasswordForm();
        librarianDataPanel = new LibrarianDataForm();
        bookManagementPanel = new BookManagementForm();
        librarianDataPanel = new LibrarianDataForm();
        librarianManagementPanel = new LibrarianManagementForm();
        readerManagementPanel = new ReaderManagementForm();
        statisticPanel = new StatisticForm();
        billManagementPanel = new BillManagementForm();
        reportPanel = new ReportForm();
        mainViewPanel.add("mainCard", booksearchPanel);
        mainViewPanel.add("changePassCard", changePasswordPanel);
        mainViewPanel.add("profileCard", librarianDataPanel);
        mainViewPanel.add("bookManagementCard", bookManagementPanel);
        mainViewPanel.add("librarianManagementCard", librarianManagementPanel);
        mainViewPanel.add("readerManagementCard", readerManagementPanel);
        mainViewPanel.add("reportCard", reportPanel);
        mainViewPanel.add("statisticCard", statisticPanel);
        mainViewPanel.add("billManagementCard", billManagementPanel);
//        card.show(mainViewPanel, "main");
    }

    public JPanel getMainViewPanel() {
        return mainViewPanel;
    }

    public JPanel getTabPanel() {
        return tabPanel;
    }

    public JPanel getLoginPanel() {
        return loginPanel;
    }

    public void setLoginSuccess(boolean loginSuccess) {
        this.loginSuccess = loginSuccess;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainViewPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        tabPanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        viewMainButton = new javax.swing.JButton();
        accountCb = new javax.swing.JComboBox<>();
        reportButton = new javax.swing.JButton();
        statisticManagerButton = new javax.swing.JButton();
        bookManagerButton = new javax.swing.JButton();
        billManagerButton = new javax.swing.JButton();
        readerManagerButton = new javax.swing.JButton();
        librarianManagerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1225, 730));
        setPreferredSize(new java.awt.Dimension(1225, 730));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Trường đại học Bách Khoa Hà Nội");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 10, 501, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Thư viện Tạ Quang Bửu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 60, 344, 42);

        mainViewPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainViewPanel);
        mainViewPanel.setBounds(0, 140, 1220, 590);

        loginPanel.setLayout(new java.awt.CardLayout());

        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginButton.setText("Đăng nhập");
        loginButton.setPreferredSize(new java.awt.Dimension(111, 25));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, "card2");

        logoutButton.setText("Đăng xuất");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        loginPanel.add(logoutButton, "card3");

        getContentPane().add(loginPanel);
        loginPanel.setBounds(1080, 20, 120, 30);

        tabPanel.setPreferredSize(new java.awt.Dimension(1220, 42));
        tabPanel.setLayout(new java.awt.CardLayout());

        defaultPanel.setPreferredSize(new java.awt.Dimension(1220, 40));

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        tabPanel.add(defaultPanel, "card2");

        functionPanel.setPreferredSize(new java.awt.Dimension(1213, 40));

        viewMainButton.setText("Trang chủ");
        viewMainButton.setPreferredSize(new java.awt.Dimension(143, 30));
        viewMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMainButtonActionPerformed(evt);
            }
        });
        functionPanel.add(viewMainButton);

        accountCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thông tin tài khoản", "Đổi mật khẩu", "Thông tin cá nhân" }));
        accountCb.setPreferredSize(new java.awt.Dimension(143, 30));
        accountCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                accountCbItemStateChanged(evt);
            }
        });
        accountCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountCbMouseClicked(evt);
            }
        });
        functionPanel.add(accountCb);

        reportButton.setText("Báo cáo");
        reportButton.setPreferredSize(new java.awt.Dimension(143, 30));
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        functionPanel.add(reportButton);

        statisticManagerButton.setText("Thống kê");
        statisticManagerButton.setPreferredSize(new java.awt.Dimension(143, 30));
        statisticManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticManagerButtonActionPerformed(evt);
            }
        });
        functionPanel.add(statisticManagerButton);

        bookManagerButton.setText("Quản lý sách");
        bookManagerButton.setPreferredSize(new java.awt.Dimension(143, 30));
        bookManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookManagerButtonActionPerformed(evt);
            }
        });
        functionPanel.add(bookManagerButton);

        billManagerButton.setText("Quản lý mượn trả");
        billManagerButton.setPreferredSize(new java.awt.Dimension(143, 30));
        billManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billManagerButtonActionPerformed(evt);
            }
        });
        functionPanel.add(billManagerButton);

        readerManagerButton.setText("Quản lý độc giả");
        readerManagerButton.setPreferredSize(new java.awt.Dimension(143, 30));
        readerManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerManagerButtonActionPerformed(evt);
            }
        });
        functionPanel.add(readerManagerButton);

        librarianManagerButton.setText("Quản lý nhân viên");
        librarianManagerButton.setPreferredSize(new java.awt.Dimension(143, 30));
        librarianManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianManagerButtonActionPerformed(evt);
            }
        });
        functionPanel.add(librarianManagerButton);

        tabPanel.add(functionPanel, "card3");

        getContentPane().add(tabPanel);
        tabPanel.setBounds(0, 100, 1220, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm(this);
        loginForm.setModal(true);
        loginForm.setLocationRelativeTo(this);
        loginForm.setVisible(true);
        if (loginSuccess) {
            CardLayout cl = (CardLayout) (tabPanel.getLayout());
            cl.next(tabPanel);
            cl = (CardLayout) (loginPanel.getLayout());
            cl.next(loginPanel);
            if (currentUser.getRole() == 0) {
                librarianManagerButton.setEnabled(false);
                librarianManagerButton.setVisible(false);
            }else if(currentUser.getRole() == 1){
                librarianManagerButton.setEnabled(true);
                librarianManagerButton.setVisible(true);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (tabPanel.getLayout());
        cl.next(tabPanel);
        cl = (CardLayout) (loginPanel.getLayout());
        cl.next(loginPanel);
        cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "mainCard");
        currentUser = null;
        booksearchPanel.resetPanel();
        bookManagementPanel.resetPanel();
        librarianManagementPanel.resetPanel();
        readerManagementPanel.resetPanel();
        billManagementPanel.resetPanel();
        reportPanel.resetPanel();
        statisticPanel.resetPanel();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMainButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "mainCard");
    }//GEN-LAST:event_viewMainButtonActionPerformed

    private void accountCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountCbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accountCbMouseClicked

    private void accountCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_accountCbItemStateChanged
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
            if (cb.getSelectedIndex() == 1) {                
                changePasswordPanel.getOldPassText().setText("");
                changePasswordPanel.getNewPassText().setText("");
                changePasswordPanel.getConfirmPassText().setText("");
                cl.show(mainViewPanel, "changePassCard");
                cb.setSelectedIndex(0);
            } else if (cb.getSelectedIndex() == 2) {
                librarianDataPanel.setInfo();
                cl.show(mainViewPanel, "profileCard");
                cb.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_accountCbItemStateChanged

    private void bookManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookManagerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "bookManagementCard");
    }//GEN-LAST:event_bookManagerButtonActionPerformed

    private void librarianManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianManagerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "librarianManagementCard");
    }//GEN-LAST:event_librarianManagerButtonActionPerformed

    private void readerManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerManagerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "readerManagementCard");
    }//GEN-LAST:event_readerManagerButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "reportCard");
    }//GEN-LAST:event_reportButtonActionPerformed

    private void statisticManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticManagerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "statisticCard");
    }//GEN-LAST:event_statisticManagerButtonActionPerformed

    private void billManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billManagerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (mainViewPanel.getLayout());
        cl.show(mainViewPanel, "billManagementCard");
    }//GEN-LAST:event_billManagerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountCb;
    private javax.swing.JButton billManagerButton;
    private javax.swing.JButton bookManagerButton;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton librarianManagerButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainViewPanel;
    private javax.swing.JButton readerManagerButton;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton statisticManagerButton;
    private javax.swing.JPanel tabPanel;
    private javax.swing.JButton viewMainButton;
    // End of variables declaration//GEN-END:variables
}
