/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LibrarianController;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Duong
 */
public class ChangePasswordForm extends javax.swing.JPanel {
    LibrarianController librarianController = new LibrarianController();
    /**
     * Creates new form ChangePasswordPanel
     */
    public ChangePasswordForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPassText = new javax.swing.JPasswordField();
        confirmPassText = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        oldPassText = new javax.swing.JPasswordField();
        oldPassLabel = new javax.swing.JLabel();
        confirmPass = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1220, 380));
        setPreferredSize(new java.awt.Dimension(1220, 578));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("Đổi mật khẩu");

        newPassLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newPassLabel.setText("Mật khẩu mới");

        oldPassLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        oldPassLabel.setText("Mật khẩu cũ");

        confirmPass.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        confirmPass.setText("Xác nhận mật khẩu");

        confirmButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        confirmButton.setText("Xác nhận");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPass)
                                    .addComponent(newPassLabel)
                                    .addComponent(oldPassLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPassText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oldPassText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPassText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(429, 429, 429))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLabel)
                    .addComponent(oldPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPassLabel)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmPass)
                                .addGap(78, 78, 78)
                                .addComponent(confirmButton))
                            .addComponent(newPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(confirmPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents
    public JPasswordField getOldPassText() {
        return oldPassText;
    }

    public JPasswordField getNewPassText() {
        return newPassText;
    }

    public JPasswordField getConfirmPassText() {
        return confirmPassText;
    }   
    
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String oldPass = new String(oldPassText.getPassword());
        String newPass = new String(newPassText.getPassword());
        String confirmPass = new String(confirmPassText.getPassword());
        if(!oldPass.equals(MainView.getCurrentUser().getPassword())){
            JOptionPane.showMessageDialog(this, "Mật khẩu không đúng");
        }else if(!newPass.equals(confirmPass)){
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không đúng");
        }else{
            if(librarianController.changePassword(newPass))
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel confirmPass;
    private javax.swing.JPasswordField confirmPassText;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JPasswordField newPassText;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JPasswordField oldPassText;
    // End of variables declaration//GEN-END:variables
}
